/*
Copyright 2014 Paul Sidnell

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package org.psidnell.omnifocus.format;

import java.io.StringWriter;

import org.junit.Test;
import org.psidnell.omnifocus.OFExport;
import org.psidnell.omnifocus.integrationtest.Diff;

public class JSONTest extends FormatTest {

    @Test
    public void testProjectMode () throws Exception {
        OFExport ofExport = new OFExport();
        ofExport.getProjectRoot().add(f1);
        ofExport.setFormat("JSON");
        ofExport.process();
        StringWriter out = new StringWriter();
        ofExport.write(out);

        Diff.diff (new String[]
            {
                "{",
                "  \"active\" : true,",
                "  \"dropped\" : false,",
                "  \"folders\" : [ {",
                "    \"active\" : true,",
                "    \"dropped\" : false,",
                "    \"folders\" : [ ],",
                "    \"id\" : \"%%%%f1\",",
                "    \"name\" : \"f1\",",
                "    \"parentFolderId\" : null,",
                "    \"projects\" : [ {",
                "      \"active\" : false,",
                "      \"completed\" : false,",
                "      \"completionDate\" : null,",
                "      \"contextName\" : null,",
                "      \"deferDate\" : null,",
                "      \"dropped\" : false,",
                "      \"dueDate\" : null,",
                "      \"dueSoon\" : false,",
                "      \"estimatedMinutes\" : -1,",
                "      \"flagged\" : false,",
                "      \"id\" : \"%%%%p1\",",
                "      \"name\" : \"p1\",",
                "      \"note\" : null,",
                "      \"onHold\" : false,",
                "      \"rank\" : 0,",
                "      \"remaining\" : true,",
                "      \"sequential\" : false,",
                "      \"singleActionList\" : false,",
                "      \"status\" : \"status\",",
                "      \"tasks\" : [ {",
                "        \"available\" : false,",
                "        \"blocked\" : false,",
                "        \"completed\" : false,",
                "        \"completionDate\" : null,",
                "        \"contextId\" : null,",
                "        \"contextName\" : null,",
                "        \"deferDate\" : 1417046400000,",
                "        \"dueDate\" : null,",
                "        \"dueSoon\" : false,",
                "        \"estimatedMinutes\" : -1,",
                "        \"flagged\" : true,",
                "        \"id\" : \"%%%%t1\",",
                "        \"name\" : \"t1\",",
                "        \"note\" : null,",
                "        \"parentTaskId\" : null,",
                "        \"projectTask\" : false,",
                "        \"rank\" : 0,",
                "        \"remaining\" : true,",
                "        \"sequential\" : false,",
                "        \"tasks\" : [ ]",
                "      }, {",
                "        \"available\" : false,",
                "        \"blocked\" : false,",
                "        \"completed\" : false,",
                "        \"completionDate\" : null,",
                "        \"contextId\" : null,",
                "        \"contextName\" : \"c1\",",
                "        \"deferDate\" : null,",
                "        \"dueDate\" : 1417046400000,",
                "        \"dueSoon\" : true,",
                "        \"estimatedMinutes\" : -1,",
                "        \"flagged\" : false,",
                "        \"id\" : \"%%%%t2\",",
                "        \"name\" : \"t2\",",
                "        \"note\" : \"line1\\nline2\",",
                "        \"parentTaskId\" : null,",
                "        \"projectTask\" : false,",
                "        \"rank\" : 0,",
                "        \"remaining\" : true,",
                "        \"sequential\" : false,",
                "        \"tasks\" : [ ]",
                "      }, {",
                "        \"available\" : false,",
                "        \"blocked\" : false,",
                "        \"completed\" : true,",
                "        \"completionDate\" : 1417046400000,",
                "        \"contextId\" : null,",
                "        \"contextName\" : \"c2\",",
                "        \"deferDate\" : null,",
                "        \"dueDate\" : null,",
                "        \"dueSoon\" : false,",
                "        \"estimatedMinutes\" : -1,",
                "        \"flagged\" : false,",
                "        \"id\" : \"%%%%t3\",",
                "        \"name\" : \"t3\",",
                "        \"note\" : \"line1\\nline2\",",
                "        \"parentTaskId\" : null,",
                "        \"projectTask\" : false,",
                "        \"rank\" : 0,",
                "        \"remaining\" : false,",
                "        \"sequential\" : false,",
                "        \"tasks\" : [ {",
                "          \"available\" : false,",
                "          \"blocked\" : false,",
                "          \"completed\" : true,",
                "          \"completionDate\" : 1417046400000,",
                "          \"contextId\" : null,",
                "          \"contextName\" : \"c2\",",
                "          \"deferDate\" : null,",
                "          \"dueDate\" : null,",
                "          \"dueSoon\" : false,",
                "          \"estimatedMinutes\" : -1,",
                "          \"flagged\" : false,",
                "          \"id\" : \"%%%%t4\",",
                "          \"name\" : \"t4\",",
                "          \"note\" : \"line1\\nline2\",",
                "          \"parentTaskId\" : null,",
                "          \"projectTask\" : false,",
                "          \"rank\" : 0,",
                "          \"remaining\" : false,",
                "          \"sequential\" : false,",
                "          \"tasks\" : [ ]",
                "        } ]",
                "      } ]",
                "    }, {",
                "      \"active\" : false,",
                "      \"completed\" : false,",
                "      \"completionDate\" : 1417046400000,",
                "      \"contextName\" : null,",
                "      \"deferDate\" : null,",
                "      \"dropped\" : false,",
                "      \"dueDate\" : 1417046400000,",
                "      \"dueSoon\" : true,",
                "      \"estimatedMinutes\" : -1,",
                "      \"flagged\" : true,",
                "      \"id\" : \"%%%%p2\",",
                "      \"name\" : \"p2\",",
                "      \"note\" : \"line1\\nline2\",",
                "      \"onHold\" : false,",
                "      \"rank\" : 0,",
                "      \"remaining\" : true,",
                "      \"sequential\" : false,",
                "      \"singleActionList\" : false,",
                "      \"status\" : \"status\",",
                "      \"tasks\" : [ ]",
                "    }, {",
                "      \"active\" : false,",
                "      \"completed\" : false,",
                "      \"completionDate\" : null,",
                "      \"contextName\" : null,",
                "      \"deferDate\" : null,",
                "      \"dropped\" : false,",
                "      \"dueDate\" : null,",
                "      \"dueSoon\" : false,",
                "      \"estimatedMinutes\" : -1,",
                "      \"flagged\" : false,",
                "      \"id\" : \"%%%%p3\",",
                "      \"name\" : \"p3\",",
                "      \"note\" : null,",
                "      \"onHold\" : false,",
                "      \"rank\" : 0,",
                "      \"remaining\" : true,",
                "      \"sequential\" : false,",
                "      \"singleActionList\" : false,",
                "      \"status\" : \"status\",",
                "      \"tasks\" : [ ]",
                "    } ],",
                "    \"rank\" : 0",
                "  } ],",
                "  \"id\" : \"__%%RootFolder\",",
                "  \"name\" : \"RootFolder\",",
                "  \"parentFolderId\" : null,",
                "  \"projects\" : [ ],",
                "  \"rank\" : 0",
                "}",
            }, out.toString().split("\n"));
    }

    @Test
    public void testContextMode () throws Exception {
        OFExport ofExport = new OFExport();
        ofExport.setProjectMode(false);
        ofExport.getContextRoot().add(c1);
        ofExport.setFormat("JSON");
        ofExport.process();
        StringWriter out = new StringWriter();
        ofExport.write(out);

        System.out.println (out);

        Diff.diff (new String[]
            {
                "{",
                "  \"active\" : true,",
                "  \"activeFlag\" : true,",
                "  \"allowsNextAction\" : true,",
                "  \"contexts\" : [ {",
                "    \"active\" : true,",
                "    \"activeFlag\" : true,",
                "    \"allowsNextAction\" : true,",
                "    \"contexts\" : [ {",
                "      \"active\" : true,",
                "      \"activeFlag\" : true,",
                "      \"allowsNextAction\" : true,",
                "      \"contexts\" : [ ],",
                "      \"dropped\" : false,",
                "      \"id\" : \"%%%%c2\",",
                "      \"name\" : \"c2\",",
                "      \"onHold\" : false,",
                "      \"parentContextId\" : null,",
                "      \"rank\" : 0,",
                "      \"tasks\" : [ {",
                "        \"available\" : false,",
                "        \"blocked\" : false,",
                "        \"completed\" : true,",
                "        \"completionDate\" : 1417046400000,",
                "        \"contextId\" : null,",
                "        \"contextName\" : \"c2\",",
                "        \"deferDate\" : null,",
                "        \"dueDate\" : null,",
                "        \"dueSoon\" : false,",
                "        \"estimatedMinutes\" : -1,",
                "        \"flagged\" : false,",
                "        \"id\" : \"%%%%t3\",",
                "        \"name\" : \"t3\",",
                "        \"note\" : \"line1\\nline2\",",
                "        \"parentTaskId\" : null,",
                "        \"projectTask\" : false,",
                "        \"rank\" : 0,",
                "        \"remaining\" : false,",
                "        \"sequential\" : false,",
                "        \"tasks\" : [ {",
                "          \"available\" : false,",
                "          \"blocked\" : false,",
                "          \"completed\" : true,",
                "          \"completionDate\" : 1417046400000,",
                "          \"contextId\" : null,",
                "          \"contextName\" : \"c2\",",
                "          \"deferDate\" : null,",
                "          \"dueDate\" : null,",
                "          \"dueSoon\" : false,",
                "          \"estimatedMinutes\" : -1,",
                "          \"flagged\" : false,",
                "          \"id\" : \"%%%%t4\",",
                "          \"name\" : \"t4\",",
                "          \"note\" : \"line1\\nline2\",",
                "          \"parentTaskId\" : null,",
                "          \"projectTask\" : false,",
                "          \"rank\" : 0,",
                "          \"remaining\" : false,",
                "          \"sequential\" : false,",
                "          \"tasks\" : [ ]",
                "        } ]",
                "      }, {",
                "        \"available\" : false,",
                "        \"blocked\" : false,",
                "        \"completed\" : true,",
                "        \"completionDate\" : 1417046400000,",
                "        \"contextId\" : null,",
                "        \"contextName\" : \"c2\",",
                "        \"deferDate\" : null,",
                "        \"dueDate\" : null,",
                "        \"dueSoon\" : false,",
                "        \"estimatedMinutes\" : -1,",
                "        \"flagged\" : false,",
                "        \"id\" : \"%%%%t4\",",
                "        \"name\" : \"t4\",",
                "        \"note\" : \"line1\\nline2\",",
                "        \"parentTaskId\" : null,",
                "        \"projectTask\" : false,",
                "        \"rank\" : 0,",
                "        \"remaining\" : false,",
                "        \"sequential\" : false,",
                "        \"tasks\" : [ ]",
                "      } ]",
                "    } ],",
                "    \"dropped\" : false,",
                "    \"id\" : \"%%%%c1\",",
                "    \"name\" : \"c1\",",
                "    \"onHold\" : false,",
                "    \"parentContextId\" : null,",
                "    \"rank\" : 0,",
                "    \"tasks\" : [ {",
                "      \"available\" : false,",
                "      \"blocked\" : false,",
                "      \"completed\" : false,",
                "      \"completionDate\" : null,",
                "      \"contextId\" : null,",
                "      \"contextName\" : \"c1\",",
                "      \"deferDate\" : null,",
                "      \"dueDate\" : 1417046400000,",
                "      \"dueSoon\" : true,",
                "      \"estimatedMinutes\" : -1,",
                "      \"flagged\" : false,",
                "      \"id\" : \"%%%%t2\",",
                "      \"name\" : \"t2\",",
                "      \"note\" : \"line1\\nline2\",",
                "      \"parentTaskId\" : null,",
                "      \"projectTask\" : false,",
                "      \"rank\" : 0,",
                "      \"remaining\" : true,",
                "      \"sequential\" : false,",
                "      \"tasks\" : [ ]",
                "    } ]",
                "  } ],",
                "  \"dropped\" : false,",
                "  \"id\" : \"__%%RootContext\",",
                "  \"name\" : \"RootContext\",",
                "  \"onHold\" : false,",
                "  \"parentContextId\" : null,",
                "  \"rank\" : 0,",
                "  \"tasks\" : [ ]",
                "}",
            }, out.toString().split("\n"));
    }
}
