-- Command: `sqlite3 "file:$HOME/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2?mode=ro" .schema`
-- OmniFocus version: 2.11.1 (v113.24 r297149)
CREATE TABLE ODOMetadata (key VARCHAR NOT NULL PRIMARY KEY, value BLOB NOT NULL);
CREATE TABLE Folder (persistentIdentifier text NOT NULL PRIMARY KEY, active integer NOT NULL, childrenCount integer NOT NULL, childrenState integer NOT NULL, creationOrdinal integer, dateAdded timestamp NOT NULL, dateModified timestamp NOT NULL, effectiveActive integer NOT NULL, name text, noteXMLData blob, numberOfAvailableTasks integer NOT NULL, numberOfContainedTasks integer NOT NULL, numberOfDueSoonTasks integer NOT NULL, numberOfOverdueTasks integer NOT NULL, numberOfRemainingTasks integer NOT NULL, parent text, plainTextNote text, rank integer NOT NULL);
CREATE TABLE Task (persistentIdentifier text NOT NULL PRIMARY KEY, blocked integer NOT NULL, blockedByFutureStartDate integer NOT NULL, childrenCount integer NOT NULL, childrenCountAvailable integer NOT NULL, childrenCountCompleted integer NOT NULL, childrenState integer NOT NULL, completeWhenChildrenComplete integer NOT NULL, containingProjectContainsSingletons integer NOT NULL, containingProjectInfo text, containsNextTask integer NOT NULL, context text, creationOrdinal integer, dateAdded timestamp NOT NULL, dateCompleted timestamp, dateDue timestamp, dateModified timestamp NOT NULL, dateToStart timestamp, effectiveContainingProjectInfoActive integer NOT NULL, effectiveContainingProjectInfoRemaining integer NOT NULL, effectiveDateDue timestamp, effectiveDateToStart timestamp, effectiveFlagged integer NOT NULL, effectiveInInbox integer NOT NULL, estimatedMinutes integer, flagged integer NOT NULL, hasCompletedDescendant integer NOT NULL, hasFlaggedTaskInTree integer NOT NULL, hasUnestimatedLeafTaskInTree integer NOT NULL, inInbox integer NOT NULL, isDueSoon integer NOT NULL, isOverdue integer NOT NULL, maximumEstimateInTree integer, minimumEstimateInTree integer, name text, nextTaskOfProjectInfo text, noteXMLData blob, parent text, plainTextNote text, projectInfo text, rank integer NOT NULL, repetitionMethodString text, repetitionRuleString text, sequential integer NOT NULL);
CREATE TABLE Setting (persistentIdentifier text NOT NULL PRIMARY KEY, creationOrdinal integer, dateAdded timestamp NOT NULL, dateModified timestamp NOT NULL, valueData blob);
CREATE TABLE Perspective (persistentIdentifier text NOT NULL PRIMARY KEY, creationOrdinal integer, dateAdded timestamp NOT NULL, dateModified timestamp NOT NULL, valueData blob);
CREATE TABLE ProjectInfo (pk text NOT NULL PRIMARY KEY, containsSingletonActions integer NOT NULL, folder text, folderEffectiveActive integer NOT NULL, lastReviewDate timestamp, minimumDueDate timestamp, nextReviewDate timestamp, nextTask text, numberOfAvailableTasks integer NOT NULL, numberOfContainedTasks integer NOT NULL, numberOfDueSoonTasks integer NOT NULL, numberOfOverdueTasks integer NOT NULL, numberOfRemainingTasks integer NOT NULL, reviewRepetitionString text, status text NOT NULL, task text, taskBlocked integer NOT NULL, taskBlockedByFutureStartDate integer NOT NULL, taskDateToStart timestamp);
CREATE TABLE Context (persistentIdentifier text NOT NULL PRIMARY KEY, active integer NOT NULL, allowsNextAction integer NOT NULL, altitude real, availableTaskCount integer NOT NULL, childrenCount integer NOT NULL, childrenState integer NOT NULL, containedTaskCount integer NOT NULL, creationOrdinal integer, dateAdded timestamp NOT NULL, dateModified timestamp NOT NULL, effectiveActive integer NOT NULL, latitude real, localNumberOfDueSoonTasks integer NOT NULL, localNumberOfOverdueTasks integer NOT NULL, locationName text, longitude real, name text, nextTaskCount integer NOT NULL, noteXMLData blob, notificationFlags integer, parent text, plainTextNote text, radius real, rank integer NOT NULL, remainingTaskCount integer NOT NULL, totalNumberOfDueSoonTasks integer NOT NULL, totalNumberOfOverdueTasks integer NOT NULL);
CREATE TABLE Attachment (persistentIdentifier text NOT NULL PRIMARY KEY, containingTransactionHint text, context text, creationOrdinal integer, dataIdentifier text, dateAdded timestamp NOT NULL, dateModified timestamp NOT NULL, folder text, name text, perspective text, previewPNGData blob, size integer NOT NULL, task text);
CREATE INDEX Folder_parent on Folder (parent);
CREATE INDEX Task_projectInfo on Task (projectInfo);
CREATE INDEX Task_parent on Task (parent);
CREATE INDEX Task_nextTaskOfProjectInfo on Task (nextTaskOfProjectInfo);
CREATE INDEX Task_context on Task (context);
CREATE INDEX Task_containingProjectInfo on Task (containingProjectInfo);
CREATE INDEX ProjectInfo_task on ProjectInfo (task);
CREATE INDEX ProjectInfo_nextTask on ProjectInfo (nextTask);
CREATE INDEX ProjectInfo_folder on ProjectInfo (folder);
CREATE INDEX Context_parent on Context (parent);
CREATE INDEX Attachment_task on Attachment (task);
CREATE INDEX Attachment_perspective on Attachment (perspective);
CREATE INDEX Attachment_folder on Attachment (folder);
CREATE INDEX Attachment_context on Attachment (context);